$(document).ready(function(){
    $(".owl-carousel").owlCarousel();
  });
var owl = $('.owl-carousel');
owl.owlCarousel({
    loop:true,
    margin:40,
    autoplay:true,
    autoplayTimeout:3000,
    autoplayHoverPause:true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
        },
        520:{
            items:2,
        },
        767:{
            items:3,
        }
    }
});
$('.play').on('click',function(){
    owl.trigger('play.owl.autoplay',[1000])
})
$('.stop').on('click',function(){
    owl.trigger('stop.owl.autoplay')
})

